#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8003 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: server1   # eureka服务端的实例名称
  client:
    registerWithEureka: false  # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false   # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:      # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://server2:8004/eureka/
    server:
      enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 8003 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8004/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************
    #保存时注意，选择 UTF-8 保存
